- name: Create resolv.conf
  template:
    src: resolv.conf.j2
    dest: "{{ dns_resolv_file }}"
    owner: root
    group: root
    mode: 0644

- name: Ensure resolv.conf is immutable
  file:
    path: /etc/resolv.conf
    attr: +i
  register: resolv_file
  changed_when: "'i' not in resolv_file.diff.before.attributes"
