# defaults file for chrony

# The package and state
chrony_package: chrony
chrony_pkg_state: present

# The configuration file
chrony_config_file: /etc/chrony.conf
chrony_config_mode: 0644

# Service options
chrony_svc: chronyd
chrony_svc_state: started
chrony_svc_enabled: yes

# The user to run commands as on remote hosts
chrony_become_user: root

# A list of servers to use with chrony and the options for each server
# Default set to public servers from the pool.ntp.org project
chrony_servers:
  - 0.rhel.pool.ntp.org
  - 1.rhel.pool.ntp.org
  - 2.rhel.pool.ntp.org
  - 3.rhel.pool.ntp.org

#Server Options:
chrony_svr_options: iburst

# Where to store the file that records the rate at which the system clock
# gains/losses time.
chrony_driftfile_path: /var/lib/chrony/drift

# Arguments for the makestep configuration option for chrony
chrony_makestep_args: 1.0 3

# Whether or not to enable kernel synchronization of the real-time clock (RTC)
chrony_enable_rtcsync: true

# The interfaces in which to enable hardware timestamping
# chrony_hwtimestamp_interfaces: *

# Define the minimum number of selectable sources required to adjust the system
# clock
# chrony_num_minsources: ~

# Set the local network from which to allow NTP client access
# chrony_ntp_client: 192.168.0.0/16

# Specify path to the file containing keys for NTP authentication
chrony_keyfile_path: /etc/chrony.keys

# Specify leapsectz
chrony_leap: right/UTC

# Specify path to the directory in which to store log files
chrony_logdir_path: /var/log/chrony

# Select which information is logged
# chrony_logged_information: measurements statistics tracking

# Set whether Chrony daemon can act as server
# chrony_svr_port: 0 

# Set network management of chrony daemon
# chrony_mgmt_port: 0
