##CHRONY

- name: Install Chrony
  package:
    name: chrony
    state: present
  when:
  - package_chrony_installed | bool    

- name: Manage Chrony service
  service:
    name: chronyd
    state: started
    enabled: yes
    
- name: Disable chrony from acting as server
  lineinfile:
    regexp: ^port
    line: port 0
    path: /etc/chrony.conf
    state: present
  when:
  - disable_chrony_as_server | bool
  notify:
  - Restart chrony service

- name: Disable network management of chrony
  lineinfile:
    regexp: ^cmdport
    line: cmdport 0
    path: /etc/chrony.conf
    state: present
  when:
  - disable_network_mangement_chrony | bool
  notify:
  - Restart chrony service


- name: Set maxpoll in /etc/chrony.conf
  block:
  - name: Ensure on Server Lines
    replace:
      path: /etc/chrony.conf
      regexp: '^(server (?:(?![ ]{{ var_chrony_option | regex_escape }} ).)*)(?:[ ]{{ var_chrony_option | regex_escape }} \S+)?(.*)$'          
      replace: '\1 {{ var_chrony_option }} {{ var_chrony_value }}\2'
  - name: Ensure on Pool Lines
    replace:
      path: /etc/chrony.conf
      regexp: '^(pool (?:(?![ ]{{ var_chrony_option | regex_escape }} ).)*)(?:[ ]{{ var_chrony_option | regex_escape }} \S+)?(.*)$'          
      replace: '\1 {{ var_chrony_option }} {{ var_chrony_value }}\2'
  when:
  - configure_chrony_max_poll | bool
