##FAPOLICYD

- name: Ensure fapolicyd is installed
  package: 
    name: fapolicyd
    state: present
  when:
  - package_fapolicyd_installation | bool
  
- name: Enable service fapolicyd service
  block:
  - name: Gather the package facts
    package_facts:
      manager: auto
  - name: Enable service fapolicyd
    service:
      name: fapolicyd
      enabled: 'yes'
      state: started
    when:
    - '"fapolicyd" in ansible_facts.packages'
  when:
  - service_fapolicyd_enabled | bool
  
- name: Check to see if fapolicyd.mounts exists
  stat:
    path: /etc/fapolicyd/fapolicyd.mounts
  register: facpolicyd_mounts_file
  when:
  - configure_fapolicyd_mounts | bool

- name: Create /etc/fapolicyd/fapolicyd.mounts if it doesn't exists
  block:
  - name: Get all current mounts and create /etc/fapolicyd/fapolicyd.mounts
    shell: mount | egrep '^tmpfs| ext4| ext3| xfs' | awk '{ printf "%s\n", $3 }' >> /etc/fapolicyd/fapolicyd.mounts
    args:
      warn: false
  when:
  - not facpolicyd_mounts_file.stat.exists
  - configure_fapolicyd_mounts | bool

- name: Re-Check to see if fapolicyd.mounts exists
  stat:
    path: /etc/fapolicyd/fapolicyd.mounts
  register: facpolicyd_mounts_file
  when:
  - configure_fapolicyd_mounts | bool

- name: Ensure proper file permissions for fapolicyd.mounts file
  file:
    path: /etc/fapolicyd/fapolicyd.mounts
    owner: root
    group: fapolicyd
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: fapolicyd_config_t
  when:
  - facpolicyd_mounts_file.stat.exists
  - configure_fapolicyd_mounts | bool

- name: Set Permissive Mode in fapolicyd.conf
  ini_file:
    option: permissive
    value: "{{ fapolicyd_permissive_mode }}"
    path: /etc/fapolicyd/facpolicyd.conf
    section:
    create: yes
  when:
  - configure_fapolicyd_permissive | bool
  notify:
    - Restart fapolicyd

- name: Add Deny all rule in fapolicyd.rules
  blockinfile:
    path: /etc/fapolicyd/fapolicyd.rules
    marker: "## {mark} Ansible Managed Block for Last Rule"
    block: |
      # Deny All if not allowed
      deny all all
  when:
  - configure_fapolicyd_deny_all_rule | bool  
  