# Main Tasks for auditd
- set_fact:
    templatevar: "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] }}"

# Packages
- name: auditd | Packages
  package:
    name: "{{ item }}"
    state: "{{ auditd_package_state }}"
  with_items: "{{ auditd_packages.split(' ') }}"

# Auditd.conf
- name: auditd | Configuration File
  template: 
    src: "{{ templatevar }}_auditd.conf.j2"
    dest: "{{ auditd_config_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart auditd

# Get list of file in /etc/audit/rules.d/
- name: Get list of .rule files in /etc/audit/rules.d/
  find:
    paths: /etc/audit/rules.d/
    patterns: "*.rules"
  register: audit_rule_files_to_delete
  when:
  - auditd_remove_all_files_in_rulesd | bool

- name: Remove all other files except for audit.rules in /etc/audit/rules.d/
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ audit_rule_files_to_delete.files }}"
  when:
  - item.path != "/etc/audit/rules.d/audit.rules"
  - auditd_remove_all_files_in_rulesd | bool

# /etc/audit/audit.rules
- name: auditd | audit.rules
  template: 
    src: "{{ templatevar }}_audit.rules.j2"
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart auditd
    
# Service
- name: auditd | Service
  service:
    name: "{{ auditd_service }}"
    state: "{{ auditd_service_state }}"
    enabled: "{{ auditd_service_enabled }}"

#Import additional tasks
- include_tasks: "{{ templatevar }}.yml"

