# audisp redhat_7 configuration
- name: auditd | RHEL 7 audispd configuration
  template: 
    src: "{{ templatevar }}{{item.src}}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart auditd
  with_items: 
    - { src: "_au-remote.conf.j2", dest: "/etc/audisp/plugins.d/au-remote.conf" }
    - { src: "_audispd.conf.j2", dest: "/etc/audisp/audispd.conf" }
    - { src: "_audisp_syslog.conf.j2", dest: "/etc/audisp/plugins.d/syslog.conf" }
    - { src: "_audisp-remote.conf.j2", dest: "/etc/audisp/audisp-remote.conf" }
