# Handlers for os hardening
- name: Restart usbguard
  service:
    state: restarted
    name: usbguard

- name: Restart sshd service
  service:
    state: restarted
    name: sshd

- name: Restart postfix service
  service:
    state: restarted
    name: postfix    

- name: Restart firewalld service
  service:
    state: restarted
    name: firewalld   

- name: Reload firewalld service
  service:
    state: reloaded
    name: firewalld   