- set_fact:
    templatevar: "{{ ansible_facts['distribution'] | lower }}_{{ ansible_facts['distribution_major_version'] }}"
    
- name: pwquality | Installation
  package:
    name: "{{ pwquality_package_name }}"
    state: present

- name: pwquality | config settings
  template:
    src: "{{ templatevar }}_pwquality.conf.j2"
    dest: "{{ pwquality_config_file_name }}"
    owner: root
    group: root
    mode: 0644

