- name: pwquality | Installation
  package:
    name: "{{ pwquality_package_name }}"
    state: present

- name: pwquality | RHEL8 settings
  template:
    src: rhel8_pwquality.conf.j2
    dest: "{{ pwquality_config_file_name }}"
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"

- name: pwquality | RHEL7 settings
  template:
    src: rhel7_pwquality.conf.j2
    dest: "{{ pwquality_config_file_name }}"
    owner: root
    group: root
    mode: 0644
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
