- name: Update hosts file
  lineinfile:
    path: "{{ hosts_file_file }}"
    owner: root
    group: root
    mode: 0644
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^127.0.0.1", line: "127.0.0.1\t{{ hosts_file_ipv4_loopback }}" }
    - { regexp: "^::1", line: "::1\t\t{{ hosts_file_ipv6_loopback }}" }
    - { regexp: "^{{ ansible_default_ipv4.address }}", line: "{{ ansible_default_ipv4.address }}\t{{ ansible_fqdn }}\t{{ ansible_hostname }}" }

