- name: modprobe disable loading
  lineinfile:
    path: "{{ modprobe_blacklist_file }}"
    create: yes
    owner: root
    group: root
    mode: 644
    state: present
    regexp: "^install {{ item }}"
    line:  "install {{ item }} /bin/true"
  with_items: "{{ modprobe_blacklist_modules.split(' ') }}"

- name: modprobe blacklisting
  kernel_blacklist:
    name: "{{ item }}"
    blacklist_file: "{{ modprobe_blacklist_file }}"
    state: present
  with_items: "{{ modprobe_blacklist_modules.split(' ') }}"
