##Defaults

## Crypto Policies
harden_crypto_policies: false
package_fipscheck_install: true
package_gnutls_install: true
enable_fips_mode: true
configure_openssl_crypto_policy: true
configure_gnutls_library: true
gnutls_crypto_line: "SYSTEM=NONE:+MAC-ALL:-MD5:+GROUP-ALL:-GROUP-X25519:-GROUP-X448:+SIGN-ALL:-SIGN-RSA-MD5:-SIGN-RSA-SHA1:-SIGN-DSA-SHA1:-SIGN-ECDSA-SHA1:-SIGN-DSA-SHA224:-SIGN-DSA-SHA256:-SIGN-DSA-SHA384:-SIGN-DSA-SHA512:-SIGN-EDDSA-ED25519:-SIGN-EDDSA-ED448:+CIPHER-ALL:-CHACHA20-POLY1305:-CAMELLIA-256-GCM:-CAMELLIA-128-GCM:-CAMELLIA-256-CBC:-CAMELLIA-128-CBC:-3DES-CBC:-ARCFOUR-128:+ECDHE-RSA:+ECDHE-ECDSA:+DHE-RSA:+VERS-ALL:-VERS-DTLS0.9:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1:-VERS-DTLS1.0:+COMP-NULL:%PROFILE_MEDIUM"
configure_sshd_system_wide_policy: true
configure_opensshserver_crypto_policy: true
opensshserver_crypto_policy: "CRYPTO_POLICY='-oCiphers=aes256-ctr,aes192-ctr,aes128-ctr -oMACs=hmac-sha2-512,hmac-sha2-256 -oGSSAPIKeyExchange=no -oKexAlgorithms=ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512 -oHostKeyAlgorithms=ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com -oPubkeyAcceptedKeyTypes=ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com -oCASignatureAlgorithms=ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-256,rsa-sha2-512'"
configure_openssh_ciphers: true
openssh_ciphers: "Ciphers aes256-ctr,aes192-ctr,aes128-ctr"
configure_openssh_macs: true
openssh_macs: "MACs hmac-sha2-512,hmac-sha2-256"

##TMUX Settings
harden_tmux: false
package_tmux_installed: true
configure_tmux_lock_after_time: true
configure_tmux_lock_command: true
configure_tmux_etc_bashrc: true
configure_tmux_etc_shells: true

##USBGUARD
harden_usbguard: false
package_usbguard_installed: true
service_usbguard_enabled: true
configure_usbguard_daemon_conf: true

##/etc/login.defs
harden_etc_login_defs: false
accounts_password_minlen_login_defs: true
var_accounts_password_minlen_login_defs: "15"
accounts_create_home_login_defs: true
var_accounts_create_home_login_defs: "yes"
accounts_encrypt_method_login_defs: true
var_accounts_encrypt_method_login_defs: SHA512
accounts_password_mindays_login_defs: true
var_accounts_password_mindays_login_defs: "1"
accounts_password_maxdays_login_defs: true
var_accounts_password_maxdays_login_defs: "60"
accounts_fail_delay_login_defs: true
var_accounts_fail_delay_login_defs: "4"
accounts_umask_login_defs: true
var_accounts_umask_login_defs: "077"

##Packages to remove
harden_remove_packages: false
package_krb5_workstation_remove: true
package_telnet_server_remove: true
package_abrt_remove: true
package_sendmail_remove: true
package_gssproxy_remove: true
package_rsh_server_remove: true
package_tftp_server_remove: true
package_vsftpd_remove: true
package_tuned_remove: true
package_iprutils_remove: true
package_xorg_x11_server_common_remove: true

##SELINUX
harden_selinux: false
package_policycoreutils_installation: true
package_policycoreutils_python_utils_installation: true
configure_selinux_policy_state: true
configure_etc_selinux_config_perms: true

##RNG
harden_rngd_service: false
package_rng_tools_installation: true
service_rngd_enabled: true

##CoreDumps
harden_coredumps: false
service_kdump_disabled: true
service_coredump_disabled: true
service_coredump_socket_disabled: true
coredump_disable_backtraces: true
disable_users_coredumps: true
coredump_disable_storage: true

##Sysctl Settings
harden_sysctl: false
sysctl_kernel_kexec_load_disabled: true
sysctl_fs_protected_symlinks: true
sysctl_fs_protected_hardlinks: true
sysctl_kernel_dmesg_restrict: true
sysctl_kernel_perf_event_paranoid: true
sysctl_kernel_randomize_va_space: true
sysctl_kernel_core_pattern: true
sysctl_net_ipv4_conf_default_accept_redirects: true
sysctl_net_ipv6_conf_default_accept_redirects: true
sysctl_net_ipv4_conf_all_send_redirects: true
sysctl_net_ipv4_icmp_echo_ignore_broadcasts: true
sysctl_net_ipv4_conf_all_accept_source_route: true
sysctl_net_ipv6_conf_all_accept_source_route: true
sysctl_net_ipv4_conf_default_accept_source_route: true
sysctl_net_ipv6_conf_default_accept_source_route: true
sysctl_net_ipv4_ip_forward: true
sysctl_net_ipv6_conf_all_forwarding: true
sysctl_net_ipv6_conf_all_accept_ra: true
sysctl_net_ipv6_conf_default_accept_ra: true
sysctl_net_ipv4_conf_default_send_redirects: true
sysctl_net_ipv4_conf_all_accept_redirects: true
sysctl_net_ipv6_conf_all_accept_redirects: true
sysctl_kernel_unprivileged_bpf_disabled: true
sysctl_kernel_yama_ptrace_scope: true
sysctl_kernel_kptr_restrict: true
sysctl_user_max_user_namespaces: true
sysctl_net_ipv4_conf_all_rp_filter: true

##File and Directory Permissions
harden_file_dirctory_permissions: false
configure_var_log_messages_permissions: true
configure_var_log_permissions: true
configure_audit_log_file_permissions: true
configure_audit_log_dir_permissions: true
configure_audit_tools_permissions: true

##/etc/dnf/dnf.conf
harden_etc_dnf_dnf_conf: false
ensure_gpgcheck_global_setting: true
ensure_localpkg_gpgcheck_global_setting: true
ensure_clean_requirements_on_remove_global_setting: true

##/etc/sysconfig/sshd
harden_etc_sysconfig_sshd: false
ensure_sshd_use_strong_rng: true
ensure_sshd_use_system_crypto_policy: true

##Modprobe Disabled items
harden_modprobe: false
configure_modprobe_uvcvideo_disabled: true
configure_modprobe_atm_disabled: true
configure_modprobe_can_disabled: true
configure_modprobe_sctp_disabled: true
configure_modprobe_tipc_disabled: true
configure_modprobe_cramfs_disabled: true
configure_modprobe_firewire_core_disabled: true
configure_modprobe_usb_storage_disabled: true
configure_modprobe_bluetooth_disabled: true

##SSHD Configuration
harden_sshd_configuration: false
package_openssh_server_installed: true
service_sshd_enabled: true
configure_sshd_config_x11uselocalhost: true
configure_sshd_config_x11forwarding: true
configure_sshd_config_rekeylimit: true
var_sshd_rekey_limit_size: 1G
var_sshd_rekey_limit_time: 1h
configure_sshd_config_printlastlog: true
configure_sshd_config_permitemptypasswords: true
configure_sshd_config_permituserenvironment: true
configure_sshd_config_permitrootlogin: true
configure_sshd_config_kerberosauthentication: true
configure_sshd_config_gssapiauthentication: true
configure_sshd_config_ignoreuserknownhosts: true
configure_sshd_config_compression: true
configure_sshd_config_strictmodes: true
configure_sshd_config_clientaliveinterval: true
configure_sshd_config_clientalivecountmax: true
configure_sshd_config_banner: true

##Postfix
harden_postfix: false
package_postfix_installed: true
service_postfix_enabled: true
configure_postfix_smtpd_client_restrictions: true
configure_postmaster_etc_aliases: true

##systemd settings
harden_systemd: false
require_singleuser_auth: true
disable_ctrlaltdel_burstaction: true
service_debug_shell_disable: true
disable_ctrlaltdel_reboot: true

##/etc/yum.repos.d settings
harden_etc_yum_repos_d: false
ensure_gpgcheck_never_disabled: true

##/tmp mount options
harden_tmp: false
mount_option_tmp_noexec: true
mount_option_tmp_nodev: true
mount_option_tmp_nosuid: true

##/dev/shm mount options
harden_dev_shm: false
mount_option_dev_shm_noexec: true
mount_option_dev_shm_nodev: true
mount_option_dev_shm_nosuid: true

##/var/log mount options
harden_var_log: false
mount_option_var_log_noexec: true
mount_option_var_log_nodev: true
mount_option_var_log_nosuid: true

##/var/log/audit mount options
harden_var_log_audit: false
mount_option_var_log_audit_noexec: true
mount_option_var_log_audit_nodev: true
mount_option_var_log_audit_nosuid: true

##/var/tmp mount options
harden_var_tmp: false
mount_option_var_tmp_noexec: true
mount_option_var_tmp_nodev: true
mount_option_var_tmp_nosuid: true

##/home mount options
harden_home: false
mount_option_home_noexec: true
mount_option_home_nodev: true
mount_option_home_nosuid: true

##/boot mount options
harden_boot: false
mount_option_boot_nosuid: true
mount_option_boot_nodev: true

##local mount options nodev
harden_local_mount_points: false
mount_option_opt_nodev: true
mount_option_usr_nodev: true
mount_option_var_nodev: true
mount_option_boot_efi_nodev: true

##Kernel Options
harden_kernel_options: false
grub2_pti_argument: true
var_pti_kernel_value: "on"
var_pti_kernel_option: pti
grub2_vsyscall_argument: true
var_vsyscall_kernel_value: "none"
var_vsyscall_kernel_option: vsyscall
grub2_slub_debug_argument: true
var_slub_kernel_value: "P"
var_slub_kernel_option: slub_debug
grub2_page_poison_argument: true
var_page_poison_kernel_value: 1
var_page_poison_kernel_option: page_poison

##UMASK
harden_umask: false
var_accounts_user_umask: "077"
accounts_umask_etc_csh_cshrc: true
accounts_umask_etc_profile: true
accounts_umask_etc_bashrc: true

##/etc/security/limits.conf
harden_etc_security_limits_conf: false
accounts_max_concurrent_login_sessions: true
var_accounts_max_concurrent_login_sessions: "10"

##/etc/security/pwquality.conf
harden_etc_security_pwquality_conf: false
accounts_password_pam_dcredit: true
var_password_pam_dcredit: "-2"
accounts_password_pam_maxclassrepeat: true
var_password_pam_maxclassrepeat: "4"
accounts_password_pam_ocredit: true
var_password_pam_ocredit: "-2"
accounts_password_pam_maxrepeat: true
var_password_pam_maxrepeat: "3"
accounts_password_pam_lcredit: true
var_password_pam_lcredit: "-2"
accounts_password_pam_difok: true
var_password_pam_difok: "8"
accounts_password_pam_minlen: true
var_password_pam_minlen: "15"
accounts_password_pam_ucredit: true
var_password_pam_ucredit: "-2"
accounts_password_pam_minclass: true
var_password_pam_minclass: "4"
accounts_password_pam_dictcheck: true
var_password_pam_dictcheck: "1"

##/etc/issue
harden_etc_issue: false
configure_etc_issue: true
var_etc_issue_text: "insert banner text here"

##/etc/ssh/ssh_config
harden_ssh_client: false
ssh_client_rekey_limit: true
var_ssh_client_rekey_limit_size: 1G
var_ssh_client_rekey_limit_time: 1h

##Packages to install
harden_install_packages: false
package_esc_install: true
package_openssl_pkcs11_install: true
package_opensc_install: true

##Sudo
harden_sudo: false
package_sudo_install: true
configure_sudoers_remove_nopasswd: true
configure_sudoers_remove_noauthenticate: true

##SSHD Certs
harden_sshd_certs: false
configure_sshd_pub_cert: true
configure_sshd_private_key: true

##Disabled Services
harden_disabled_services: false
service_autofs_disabled: true

##Firewalld
harden_firewalld: false
package_firewalld_install: true
package_nftables_install: true
service_firewalld_enabled: true
configure_firewalld_backend: true
firewalld_active_zone_drop: true

##CHRONY
harden_chrony: true
package_chrony_installed: true
disable_chrony_as_server: true
disable_network_mangement_chrony: true
configure_chrony_max_poll: true
var_chrony_option: maxpoll
var_chrony_value: 16

##/etc/default/useradd
harden_etc_default_useradd: false
configure_etc_default_useradd: true
value_useradd_inactive: "35"

##AIDE
harden_aide: false
package_aide_install: true
package_mailx_install: true
configure_aide_cronjob: true
aide_email_address: "root"
configure_aide_verify_audit_tools: true
configure_aide_content_item: true
create_aide_database: true

##Rsyslog
harden_rsyslog: false
package_rsyslog_install: true
service_rsyslog_enabled: true
configure_rsyslog_log_all_cron_facilities: true
configure_rsyslog_log_all_auth_facilities: true
configure_rsyslog_remote_offloading: true
rsyslog_remote_type: "@@"
rsyslog_remote_server_port: "0.0.0.0:514"

##SSSD
harden_sssd: false
package_sssd_installation: true
package_sssd_tools_installation: true
service_sssd_enabled: true
configure_sssd_offline_cache_credentials_expiration: true
configure_sssd_certificate_verification: true

##Fapolicyd
harden_fapolicyd: false
package_fapolicyd_installation: true
service_fapolicyd_enabled: true
configure_fapolicyd_mounts: true
configure_fapolicyd_permissive: true
fapolicyd_permissive_mode: "1"
configure_fapolicyd_deny_all_rule: true

##PAM
harden_pam: false
configure_pam_postlogin_lastlog: true
configure_pam_rounds_pam_unix: true
configure_pam_sha512_pam_unix: true
configure_pam_nullok_pam_unix: true
configure_pam_pwhistory: true
configure_pam_pwquality: true
configure_pam_faillock_preauth: true
configure_pam_faillock_authfail: true
configure_pam_faillock_account: true
configure_etc_security_faillock_conf: true
faillock_dir_records: "/var/log/faillock"

##Audit
harden_auditing: false
package_audit_install: true
service_auditd_enabled: true
grub2_audit: true
var_audit_kernel_value: 1
var_audit_kernel_option: audit
grub2_audit_backlog_limit: true
var_audit_backlog_kernel_value: 8192
var_audit_backlog_kernel_option: audit_backlog_limit
configure_etc_audit_auditd_conf_permissions: true
configure_auditd_conf_action_mail_acct: true
var_action_mail_acct: "root"
configure_auditd_conf_disk_error_action: true
var_disk_error_action: "SYSLOG"
configure_auditd_conf_max_log_file_action: true
var_max_log_file_action: "ROTATE"
configure_auditd_conf_disk_full_action: true
var_disk_full_action: "SYSLOG"
configure_auditd_conf_local_events: true
var_local_events: "yes"
configure_auditd_conf_name_format: true
var_name_format: "hostname"
configure_auditd_conf_log_format: true
var_log_format: "ENRICHED"
configure_auditd_conf_overflow_action: true
var_overflow_action: "SYSLOG"
configure_auditd_conf_space_left: true
var_space_left: "25%"
configure_auditd_conf_space_left_action: true
var_space_left_action: "EMAIL"
configure_permissions_audit_log_file: true
configure_audit_rules: true
configure_audit_rule_faillock_log_dir: true
configure_loginuid_immutable_audit_rule: true
configure_immutable_bit_audit_rule: true
var_immutable_bit: "2"
configure_auditd_rule_files_permissions: true

